"""
AI Analyzer
===========
Uses Google Gemini to produce a structured Markdown trade-opportunities report
from the raw data collected by DataCollector.

Falls back to a rule-based template report when no GEMINI_API_KEY is set,
so the service is still functional during local development / evaluation.
"""

import json
import logging
from datetime import datetime
from typing import Any

import httpx

from config import settings

logger = logging.getLogger("ai_analyzer")

GEMINI_ENDPOINT = (
    "https://generativelanguage.googleapis.com/v1beta/models/"
    "{model}:generateContent?key={key}"
)

SYSTEM_PROMPT = """You are an expert trade analyst specializing in Indian markets.
Your task is to produce a concise, structured Markdown report on trade opportunities
for the given sector in India, based on the provided market snippets.

The report MUST follow this exact structure:

# Trade Opportunities Report: {sector}
*Generated: {date}*

## Executive Summary
(2-3 sentence overview of the sector's trade outlook)

## Current Market Overview
(Key market statistics, size, growth rate)

## Top Trade Opportunities
(3-5 specific, actionable opportunities with brief explanation)

## Export Potential
(Key export destinations, products, value)

## Import Trends
(What India is importing, from where, and why)

## Key Drivers & Challenges
### Drivers
- (list)
### Challenges
- (list)

## Government Policies & Initiatives
(Relevant schemes, PLI, FTAs, etc.)

## Investment Outlook
(FDI trends, key players, investment hotspots)

## Recommendations
(3-4 actionable recommendations for traders/investors)

## Data Sources
(List the sources used, with URLs if available)

---
*Report generated by Trade Opportunities API | Data as of {date}*

Use only the provided snippets as your source material. Be specific with numbers
where data allows. Write in a professional, analyst tone.
"""


class AIAnalyzer:
    def __init__(self) -> None:
        self.api_key = settings.GEMINI_API_KEY
        self.model   = settings.GEMINI_MODEL
        self.timeout = httpx.Timeout(60.0)

    # ── Public API ──────────────────────────────────────────────────────────────

    async def analyze(self, sector: str, raw_data: dict[str, Any]) -> str:
        """
        Generate a Markdown report.

        Uses Gemini when GEMINI_API_KEY is available; otherwise generates a
        structured fallback report from the raw snippets.
        """
        if self.api_key:
            return await self._gemini_analyze(sector, raw_data)
        else:
            logger.warning("GEMINI_API_KEY not set – using fallback report generator.")
            return self._fallback_report(sector, raw_data)

    # ── Gemini integration ──────────────────────────────────────────────────────

    async def _gemini_analyze(self, sector: str, raw_data: dict[str, Any]) -> str:
        today = datetime.utcnow().strftime("%B %d, %Y")
        snippets_text = self._format_snippets(raw_data.get("snippets", []))

        prompt = (
            SYSTEM_PROMPT.format(sector=sector.title(), date=today)
            + "\n\n## Collected Market Data\n\n"
            + snippets_text
        )

        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.4,
                "maxOutputTokens": 2048,
            },
        }

        url = GEMINI_ENDPOINT.format(model=self.model, key=self.api_key)

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            resp = await client.post(url, json=payload)
            resp.raise_for_status()
            data = resp.json()

        # Extract generated text
        try:
            return data["candidates"][0]["content"]["parts"][0]["text"]
        except (KeyError, IndexError) as exc:
            raise RuntimeError(f"Unexpected Gemini response shape: {exc}\n{json.dumps(data)[:500]}")

    # ── Fallback report ─────────────────────────────────────────────────────────

    def _fallback_report(self, sector: str, raw_data: dict[str, Any]) -> str:
        """
        Generate a structured report from raw snippets without an LLM.
        Used when GEMINI_API_KEY is not configured.
        """
        today  = datetime.utcnow().strftime("%B %d, %Y")
        title  = sector.title()
        snips  = raw_data.get("snippets", [])

        sources_md = "\n".join(
            f"- [{s['title']}]({s['url']})" for s in snips if s.get("url")
        ) or "- DuckDuckGo search results"

        highlights = "\n".join(
            f"- **{s['title']}**: {s['snippet']}"
            for s in snips[:6]
            if s.get("snippet")
        ) or "- No data snippets available."

        return f"""# Trade Opportunities Report: {title}
*Generated: {today}*

> ⚠️ **Note:** This report was generated without an AI model (GEMINI_API_KEY not configured).
> Set `GEMINI_API_KEY` in your environment for full AI-powered analysis.

---

## Executive Summary

The **{title}** sector in India presents significant trade opportunities driven by
government initiatives, growing domestic demand, and expanding export markets.
This report summarizes current market intelligence gathered from recent news and
industry sources.

## Current Market Overview

India's {title} sector is among the key contributors to the country's GDP and
export basket. The sector continues to attract Foreign Direct Investment (FDI)
and benefits from several government-backed incentive schemes.

## Latest Market Intelligence

{highlights}

## Top Trade Opportunities

1. **Export Expansion** – Leverage India's competitive cost advantage and
   skilled workforce to increase exports to ASEAN, Africa, and Western markets.
2. **Import Substitution** – Opportunities to replace high-value imports with
   domestically manufactured alternatives through PLI schemes.
3. **Technology Collaboration** – Joint ventures and technology transfer
   agreements with global leaders.
4. **FDI Attraction** – Greenfield and brownfield investment opportunities
   aided by liberalised FDI norms.
5. **E-Commerce & Digital Trade** – Growing cross-border digital trade channels
   opening new B2B and B2C avenues.

## Government Policies & Initiatives

- **Production-Linked Incentive (PLI) Scheme** – Direct financial incentives
  for incremental sales in key sectors.
- **Make in India** – Encourages domestic manufacturing and reduces import
  dependence.
- **National Export Policy** – Sector-specific export promotion councils and
  market development funds.
- **Free Trade Agreements (FTAs)** – India's expanding FTA network with UAE,
  Australia, and ongoing negotiations with the EU and UK.

## Investment Outlook

India's stable macroeconomic environment, large consumer base, and improving
ease-of-doing-business rankings make the {title} sector attractive for both
domestic and international investors.

## Recommendations

1. Monitor government PLI and export-incentive notifications for the {title}
   sector closely.
2. Engage with the relevant Export Promotion Council for market-specific data.
3. Explore bilateral trade opportunities through India's FTA partners.
4. Invest in supply-chain resilience to mitigate global disruption risks.

## Data Sources

{sources_md}

---
*Report generated by Trade Opportunities API | Data as of {today}*
"""

    # ── Utility ─────────────────────────────────────────────────────────────────

    @staticmethod
    def _format_snippets(snippets: list[dict]) -> str:
        if not snippets:
            return "*No snippets collected.*"
        lines = []
        for i, s in enumerate(snippets, 1):
            lines.append(f"**[{i}] {s.get('title', 'No title')}**")
            lines.append(s.get("snippet", ""))
            if s.get("url"):
                lines.append(f"Source: {s['url']}")
            lines.append("")
        return "\n".join(lines)
